name: Auto Login Serv00

on:
  schedule:
    - cron: '0 13 */60 * *'  # 每60天的13:00（UTC时间）执行
  workflow_dispatch:          # 保留手动触发功能

jobs:
  login:
    runs-on: ubuntu-latest
    timeout-minutes: 5        # 添加超时限制

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 升级到最新版

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'    # 升级到LTS版本
        cache: 'npm'          # 启用依赖缓存

    - name: Install dependencies
      run: npm ci             # 更安全的依赖安装方式

    - name: Execute login
      run: npm start
      env:
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        LOGIN_INFO: ${{ secrets.LOGIN_INFO }}
